version: '3.8'
services:
  openeyeemployeeservice:
    container_name: openeyeemployeeservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb/openeye?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - eureka.client.service-url.defaultZone=http://openeyeserviceregistry:8761/eureka/
      - eureka.client.enabled=true
      - eureka.host=openeyeserviceregistry
      - eureka.instance.preferIpAddress=false
      - eureka.instance.hostname=localhost
     
    networks:
      - springboot-net
    restart: on-failure
networks:
  springboot-net:
    name: springboot-net
    external: true