management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9091
spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://192.168.1.47:8888
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
